version: "3"
services:
  api:
    container_name: FastAPI
    build:
      context: ./api
      dockerfile: api.Dockerfile
    volumes:
      - ./api:/api
    ports:
      - "9004:9004"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 9004
    env_file:
      - ./api.env